# Generated by Django 5.2.1 on 2025-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
