# Generated by Django 5.2.1 on 2025-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_list_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='is_done',
        ),
        migrations.AddField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
