# Generated by Django 5.2.1 on 2025-05-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_list_is_done_list_completed_alter_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='completed',
            new_name='is_done',
        ),
    ]
